version: "3.3"
services:
  aoc:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - aoc-net
    secrets:
      - settings

  postgres:
    image: 'postgres:13.1-alpine'
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - aoc-net

networks:
  aoc-net:

volumes:
  db-data:

secrets:
  settings:
    file: ./settings.json
